name: Continuous Deployment

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: hilare/streamlit-tellco-analytics-app:latest

    - name: Set up kubeconfig
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.8'

#    - name: Deploy to Kubernetes
#      run: |
#        kubectl config set-cluster kubernetes --server=${{ secrets.KUBERNETES_SERVER }}
#        kubectl config set-credentials github-action --token=${{ secrets.KUBERNETES_TOKEN }}
#        kubectl config set-context default --cluster=kubernetes --user=github-action
#        kubectl config use-context default
#        kubectl apply -f kubernetes/deployment.yaml
#        kubectl rollout status deployment/my-python-app-deployment
